language: elixir
matrix:
  include:
    - os: linux
      sudo: required
      otp_release: 21.0
      elixir: 1.8.0
sudo: false
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install inotify-tools; fi
before_script:
  - mix deps.get
script:
  - mix test
  - mix credo
  - mix format --check-formatted --dry-run
env:
  - CI=true